# Generated by Django 5.0 on 2026-04-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_commissionbracket'),
        ('sales', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionbracket',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_brackets', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='commissionbracket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_brackets', to=settings.AUTH_USER_MODEL),
        ),
    ]
