# Generated by Django 5.0 on 2026-04-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_commissionbracket_sale_commissionbracket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionbracket',
            name='created_by',
        ),
    ]
