# Generated by Django 6.0.4 on 2026-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_commissionbracket_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('SELLER', 'Seller'), ('CLEANER', 'Cleaner'), ('BOTH', 'Seller + Cleaner')], default='SELLER', max_length=20),
        ),
    ]
