# Generated by Django 6.0.4 on 2026-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('SOLD', 'Sold'), ('NO_ANSWER', 'No Answer'), ('REJECTED', 'Rejected'), ('NON_DM', 'Non DM'), ('COME_BACK', 'Come Back'), ('LEAD', 'Lead')], default='NO_ANSWER', max_length=20),
        ),
    ]
