# Generated by Django 5.0 on 2026-04-14 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('WINDOW_WASH', 'Window Wash'), ('PRESSURE_WASH', 'Pressure Wash'), ('GUTTER_CLEAN', 'Gutter Clean'), ('OTHER', 'Other')], default='WINDOW_WASH', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('estimated_time', models.PositiveIntegerField(default=60, help_text='Minutes')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_cleaner', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLEANER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
