# Generated by Django 5.0 on 2026-04-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobcleaner'),
        ('sales', '0002_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='job',
            name='estimated_time',
            field=models.PositiveIntegerField(default=120, help_text='Minutes'),
        ),
        migrations.AddField(
            model_name='jobcleaner',
            name='cleaner',
            field=models.ForeignKey(limit_choices_to={'role': 'CLEANER'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_cleaner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcleaner',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaners', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='jobcleaner',
            unique_together={('job', 'cleaner')},
        ),
    ]
