# Generated by Django 6.0.4 on 2026-04-20 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_sale_alter_job_estimated_time_jobcleaner_cleaner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assigned_cleaner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['CLEANER', 'BOTH']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobcleaner',
            name='cleaner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['CLEANER', 'BOTH']}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_as_cleaner', to=settings.AUTH_USER_MODEL),
        ),
    ]
