# Generated by Django 5.0 on 2026-04-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_job_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
