# Generated by Django 5.0 on 2026-04-14 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doors_knocked', models.PositiveIntegerField(default=0)),
                ('houses_sold', models.PositiveIntegerField(default=0)),
                ('no_answer', models.PositiveIntegerField(default=0)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('non_dm', models.PositiveIntegerField(default=0)),
                ('come_back', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
