# Generated by Django 5.0 on 2026-04-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_first_job_date'),
        ('geolocation', '0002_alter_house_status'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SOLD', 'Sold'), ('NO_ANSWER', 'No Answer'), ('REJECTED', 'Rejected'), ('NON_DM', 'Non DM'), ('COME_BACK', 'Come Back'), ('LEAD', 'Lead')], default='NO_ANSWER', max_length=20)),
                ('open_day', models.DateTimeField(blank=True, help_text='Scheduled open day if customer agreed', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customers.customer')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='geolocation.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'ordering': ['-created_at'],
            },
        ),
    ]
