# Generated by Django 6.0.4 on 2026-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quote_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
